### ISSUE TITLE
Install a bunch of R libraries

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/farallon-image#2]
@trondkr requested the following R packages be installed: 

`parallel itsadug TMB VAST EOFR INLA car lme4 MASS MuMIn mediation nlsem lavaan semPlot mgcv mgcViz DHARMa dunn.test corrplot statmod tweedie glmmTMB data.table rgeos sf sp raster rgdal purrr ggpubr ggstance gplots gganimate splitstackshape rworldmap maptools mapdata legendMap grid rnaturalearth rnaturalearthdata viridis adehabitatMA ncdf4`

This would need to be added to https://github.com/2i2c-org/2i2c-pangeo-hubs/blob/staging/deployments/ohw/image/install.R. We should pin each package to current version, available via https://packagemanager.rstudio.com/client/#/repos/1/packages

**Comment by GeorgianaElena** [comment]
Closed by https://github.com/2i2c-org/pangeo-hubs/pull/6 :tada:

**Comment by choldgraf** [comment]
Hey all - I think this one never got deployed (at least, I see an ❌ in the deployment field)

**Comment by yuvipanda** [comment]
I need to open an issue about getting the GitHub actions fixed, @choldgraf. Currently this is deployed manually.

**Comment by caitlinkroeger** [comment]
Hello! Apologies if this is not the appropriate place for this request (I'm still learning how to use GitHub). I would like to request an update of the VAST package to the latest 3.7.0 version. Please let me know if I should open a new issue for this.

**Comment by yuvipanda** [comment]
@caitlinkroeger heya! I'll try to get this done over the weekend, and if not by Monday.

**Comment by caitlinkroeger** [comment]
Thank you @yuvipanda - I'll keep an eye out for the update!

**Comment by caitlinkroeger** [comment]
Hi! Just curious if any progress on updating VAST? Thank you!

**Comment by yuvipanda** [comment]
@caitlinkroeger can you check now? Hopefully over the next week or two we'll be able to migrate the farallon hub to our new infrastructure setup (https://github.com/2i2c-org/pilot-hubs/issues/368) that will make these kinda updates faster. Apologies for the delay in this case.

**Comment by caitlinkroeger** [comment]
Thank you for working on updating the VAST package! I received the
following warning when I loaded the package:

Warning message:
In checkMatrixPackageVersion() : Package version inconsistency detected.
TMB was built with Matrix version 1.3.4
Current Matrix version is 1.3.2
Please re-install 'TMB' from source using install.packages('TMB', type
= 'source') or ask CRAN for a binary version of 'TMB' matching CRAN's
'Matrix' package

**Comment by yuvipanda** [comment]
@caitlinkroeger I've updated the version of the 'matrix' package too! I've also moved the farallon hub to a different cluster - but nothing should be different from your end! Can you let us know if anything seems off? Thanks

**Comment by caitlinkroeger** [comment]
Hello! Thank you for the update! The VAST installation is working well but
I am trying to plot some maps from the model output with code that worked
before the update and I'm getting an error that I need the package
'lwgeom'. Is emailing here okay for such requests or is there a better
place to ask for package installations in the future? Thank you!

**Comment by choldgraf** [comment]
hey @caitlinkroeger - think you could open a new issue about this new package? I think that'll be easier to track than using this issue. You could use this issue template to do so: https://github.com/2i2c-org/pilot/issues/new?labels=enhancement&template=tech-request.md
