### ISSUE TITLE
Add simple GitHub authentication to Farallon hub

### ISSUE THREAD

**Issue by trondkr** [2i2c-org/farallon-image#21]
It would be great if we could add authentication to the Farallon Institute server so that only Github users that work at Farallon can use the server. Could that be done if we submit to you a list of Github usernames?

Thank you. Cheers, Trond

**Comment by yuvipanda** [comment]
For this, let's:

1. Create a new GitHub organization (say, 'farallon-2i2c')
2. Give folks admin access to this GitHub organization
3. Setup the hub to allow anyone who is part of the organization
4. Now folks can add / remove users as they wish by using this GitHub organization

This allows for easy delegation of access control and gets us out of the loop.

**Comment by choldgraf** [comment]
@yuvipanda is there any way that we can restrict hub access to specific *teams* within an organization? That might be a more scalable option than needing to create a new github organization for every new Pangeo hub we want to deploy. (and who knows if GitHub organizations will always be infinite and free to create). Or, if this is just a one-off solution right now until we figure out something else in the future, that's fine with me too as long as we make that explicit

**Comment by rabernat** [comment]
We use auth0 rules to do this in our current pangeo hubs.

https://github.com/pangeo-data/pangeo-cloud-federation/tree/staging/auth0

**Comment by yuvipanda** [comment]
That's really cool, @rabernat! That's what we should use too.

Let's see how we can make these two repos be as exactly the same as possible...

**Comment by choldgraf** [comment]
agree @rabernat that is nifty!

**Comment by yuvipanda** [comment]
For now, let's just use GitHub based auth for Farallon.

Let's discuss more general auth in #12

**Comment by GeorgianaElena** [comment]
> For now, let's just use GitHub based auth for Farallon.

I opened #24 that allows only the members of the `farallon-2i2c` and `2i2c-org` GitHub organizations to login with GitHub into the hubs. This is currently deployed to the ohw staging to be tested.

@trondkr, do you want to create the `farallon-2i2c` GitHub org and add members to it as @yuvipanda  suggested in the [first comment](https://github.com/2i2c-org/pangeo-hubs/issues/21#issuecomment-728813252)? After this, we can deploy it to prod :rocket:

**Comment by yuvipanda** [comment]
@GeorgianaElena \o/ thank you for working on it! I think you can create the org yourself, and just add @trondkr as an admin. How does that sound?

**Comment by GeorgianaElena** [comment]
Perfect :+1:

**Comment by GeorgianaElena** [comment]
I created the org here: https://github.com/farallon-2i2c and sent an invite to @trondkr to be an owner/admin :rocket:

**Comment by yuvipanda** [comment]
To push this along, @GeorgianaElena can you:

1. Login to the Farallon hub and find list of users who have logged in
2. Invite them all to the GitHub org
3. And let's decide on a switchover date?

**Comment by GeorgianaElena** [comment]
@yuvipanda, I don't think I'm an admin user (I don't see the admin panel). Is there another way of seeing which users have logged in other than checking the admin panel?

**Comment by yuvipanda** [comment]
@GeorgianaElena ah, I think the easiest thing to do is maybe do add yourself to the list of admins (via a deployment), and then use that to check who are the users who have logged in. Can you give that a try?

**Comment by trondkr** [comment]
@yuvipanda @GeorgianaElena 
Yesterday I added several FI members to the organization

**Comment by GeorgianaElena** [comment]
Awesome @trondkr :tada: Thank you! Do you want to wait a bit longer to add more members or should we deploy this to the prod hub already?

**Comment by trondkr** [comment]
Feel free to deploy. I think we have added most users now. Thanks! T.


På 11. desember 2020 kl. 08:40:55, Georgiana Elena (notifications@github.com)
skrev:

Awesome @trondkr <https://github.com/trondkr> 🎉 Thank you! Do you want to
wait a bit longer to add more members or should we deploy this to the prod
hub already?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/2i2c-org/pangeo-hubs/issues/21#issuecomment-743299523>,
or unsubscribe
