### ISSUE TITLE
Duplicate launcher entries

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/farallon-image#22]
On the staging hubs, where the pangeo/pangeo-notebook is used as the base image as per https://github.com/2i2c-org/pangeo-hubs/pull/15, some of the launcher entries show up two times, but the environment is the same:

![duplicates](https://user-images.githubusercontent.com/7579677/99371381-816ded00-28c7-11eb-833f-5ef3ce36d37a.png)

We should probably find a way to get rid of one of these.

**Comment by yuvipanda** [comment]
@GeorgianaElena ooh, good catch. Let's explicitly uninstall nb-conda-kernels for now, and open an issue about it? I think that's where they're coming from.
