### ISSUE TITLE
Provide more visibility into cloud resources being used

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/farallon-image#27]
It's practically not possible right now for *hub* admins to know what exactly their cloud resources are. This *will* lead to surprise bills. If the hub admins are also AWS admins, this is *kinda* ok, but not generally.

We should have at least *some* form of resource usage reporting in terms of what cloud resources are being paid for. 

Some simple UI over https://cloudquery.io/ might be a good start.

**Comment by rothgar** [comment]
I'm pretty sure [Lens](https://github.com/lensapp/lens) is able to track cloud resources used by workloads in a cluster.

The new EKS console that launched last year also has a roadmap goal to be usable from non-EKS clusters and include AWS resources that are attached to k8s workloads. https://aws.amazon.com/blogs/containers/introducing-the-new-amazon-eks-console/
