### ISSUE TITLE
Integrate with Pangeo Docker Images

### ISSUE THREAD

**Issue by rabernat** [2i2c-org/farallon-image#3]
It's great to see the pangeo 2i2c hubs moving forward.

We have put a HUGE amount of work into our CI-based docker image building infrastructure: https://github.com/pangeo-data/pangeo-docker-images/
Lots of coordination is required to ensure consistency between packages versions, particularly where dask-gateway is involved.

Most of our existing hubs just pass through this image: https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/deployments/gcp-uscentral1b/image/binder/Dockerfile

It's very important to me that this work and innovation be used to inform 2i2c, particularly when it comes to pangeo-branded hubs.

As a first step, could we just use the Pangeo docker images? That would immediately solve issues like #1.

**Comment by yuvipanda** [comment]
Absolutely, @rabernat. Should definitely base this off that. I'll spend some time on it next week.

#1 was this using the default z2jh image, and a config issue, so would've been there regardless.

**Comment by yuvipanda** [comment]
https://github.com/pangeo-data/pangeo-docker-images/pull/156 starts the process. My end-goal here is to have an image with R in the upstream pangeo-docker-images repo.

**Comment by yuvipanda** [comment]
@GeorgianaElena has now deployed this, and we're using the PANGEO image as our base.
