### ISSUE TITLE
Closing all of the issues in this repository

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/farallon-image#31]
This repository was used for the original Farallon hub, but I think that it is now decommissioned: 

- https://github.com/2i2c-org/infrastructure/issues/1454

So I'm going to close all of the Farallon-related issues here and in other repositories in a few hours, unless somebody directs me to do otherwise!

**Comment by yuvipanda** [comment]
yesss!

**Comment by damianavila** [comment]
💯
