### ISSUE TITLE
R Studio library installation

### ISSUE THREAD

**Issue by caitlinkroeger** [2i2c-org/farallon-image#9]
Hello! At Farallon here. In R Studio, I tried to use the installed package 'mgcViz' but library(mgcViz) returned "package 'rgl' could not be loaded" 

It would be great if the following packages could also be installed: Information, corrplot, and ClustOfVar

Thank you!

**Comment by yuvipanda** [comment]
Thanks for opening this, @caitlinkroeger! 

For the `rgl` issue, I looked at the page for package `rgl` - https://packagemanager.rstudio.com/client/#/repos/1/packages/rgl and found that it needed a few more system packages (apt packages) to be installed. In particular, I think installing `libglu1-mesa-dev` and `libgl1-mesa-dev` should probably fix it.

The other packages should just be standard installs I guess.

@GeorgianaElena thanks for tackling this!
